# This file was generated by GoReleaser. DO NOT EDIT.
cask "stado" do
  version "0.48.0"

  on_macos do
    on_intel do
      sha256 "f1119f72d929e90bd0cec6d9877d77be70fe68ed892f20868a138c7a66b054c5"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40a109671b3a942880a922bcdba2fe380bb638c74836dac0fd36af4fa6a8a662"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8e51f646e6c3bce027eb375de45b2573932b72acfd9c9f36033d894b4ca0405"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e3753115f2116c402150cf761d3c941ac624100c827f93794fd54cd0ab3b7d7"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stado"
  desc "Sandboxed, git-native coding-agent runtime"
  homepage "https://github.com/foobarto/stado"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stado"

  # No zap stanza required

end
