# This file was generated by GoReleaser. DO NOT EDIT.
cask "stado" do
  version "0.36.0"

  on_macos do
    on_intel do
      sha256 "f32f1dcf60ee79e4751f0091ff2d80617a43af2149d49ecd983b83672b6e5df4"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d0c094f4ca4ea0ad91346ab2cb79f351ffb8ccf953e05a467ba344d082cf562"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12e07bca8bd21314afe88cfb2f22fa45ab0ae8c960590e0337495b5affbb5d68"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "97723cad2d9f51523b42f23a63933b48059e0f1d5169270c20202febf3ef7ab1"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stado"
  desc "Sandboxed, git-native coding-agent runtime"
  homepage "https://github.com/foobarto/stado"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stado"

  # No zap stanza required

end
