# This file was generated by GoReleaser. DO NOT EDIT.
cask "stado" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "ab09e33e58723e6a42bc64cbe7c92384206c3740aa86ec143a21074bcea89238"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "043fb4df9feae4a61c113fb2f731f208d72b2f0e5d9d50134188cce06fb50540"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d917082905fb250aee6133eda18ce6717234fc839ce78ce66e9e538c02d46dd"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "586349c46fa652893514e6d870a28d686103b6bcafa5944d0a999e89126141cd"
      url "https://github.com/foobarto/stado/releases/download/v#{version}/stado_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stado"
  desc "Sandboxed, git-native coding-agent runtime"
  homepage "https://github.com/foobarto/stado"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stado"

  # No zap stanza required

end
