# typed: false
# frozen_string_literal: true

# Homebrew formula for Glorbo — filesystem-first agent orchestration.
#
# Pre-1.0. Linux: full kernel-sandboxed agent runtime via bwrap
# (GEP-5). macOS: degraded mode — agents run unsandboxed because
# bwrap has no macOS equivalent yet. See caveats.
#
# AUTO-GENERATED by `mix glorbo.release_formula` — do not edit
# by hand. Regenerate after each release:
#
#   gh release create vX.Y.Z ...
#   mix glorbo.release_formula --write
class Glorbo < Formula
  desc "Filesystem-first agent orchestration (Elixir/OTP + Phoenix LiveView)"
  homepage "https://github.com/foobarto/glorbo"
  version "0.13.0"
  license "Apache-2.0"

  on_linux do
    # bwrap is the kernel-enforced sandbox around every agent
    # subprocess (GEP-5 D4). Linux-only: macOS has no equivalent
    # yet.
    depends_on "bubblewrap"

    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.13.0/glorbo-linux-x86_64"
      sha256 "53c025e9130bd2cec2b7b7f1cac10764b29483d3c96531be797446b7bf09f7a6"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.13.0/glorbo-linux-aarch64"
      sha256 "f9ec49c18078a6e55a6ba75e822bfdcacf423ec11264824e48907f741a3a9ceb"
    end
  end

  on_macos do
    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.13.0/glorbo-darwin-x86_64"
      sha256 "207ae648afe17e5f11582c0daeb728996193f8b18ce5cce397c52d7a96352a35"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.13.0/glorbo-darwin-arm64"
      sha256 "236b4017fea1c3b7750e8289d9163898a82a71459508b09cf528f05f1f4ad88d"
    end
  end

  def install
    # Burrito ships a single self-contained binary. Pick the right
    # downloaded file by OS + CPU and rename to `glorbo`.
    binary =
      if OS.mac?
        Hardware::CPU.intel? ? "glorbo-darwin-x86_64" : "glorbo-darwin-arm64"
      else
        Hardware::CPU.intel? ? "glorbo-linux-x86_64" : "glorbo-linux-aarch64"
      end

    bin.install binary => "glorbo"
    chmod 0755, bin/"glorbo"
  end


  def caveats
    <<~EOS
      Glorbo is pre-1.0. APIs, CLI flags, on-disk layout, and the
      SQLite schema may change between minor versions.

      First-run setup:
        glorbo doctor          # verify host prerequisites
        glorbo init            # scaffold ~/.glorbo/ with an acme example
        glorbo up              # start the dashboard on :4000

      Platform notes:

      Linux  — agents run in a bwrap-sandboxed subprocess (GEP-5).
               `brew install bubblewrap` is declared as a dep.

      macOS  — experimental. Agents run UNSANDBOXED because bwrap
               has no macOS equivalent yet. `glorbo doctor` flags
               this with a warning; a single audit row lands at
               first dispatch (`agent.sandbox_unavailable`).
               FSEvents covers the filesystem-watcher side.

      Docs: #{homepage}
    EOS
  end

  test do
    # Doctor in JSON mode returns the version + check list.
    output = shell_output("#{bin}/glorbo doctor --json")
    assert_match(/"version":\s*"0\\.13\\.0"/, output)
    assert_match(/"checks":/, output)
  end
end
