# typed: false
# frozen_string_literal: true

# Homebrew formula for Glorbo — filesystem-first agent orchestration.
#
# Pre-1.0. Linux: full kernel-sandboxed agent runtime via bwrap
# (GEP-5). macOS: degraded mode — agents run unsandboxed because
# bwrap has no macOS equivalent yet. See caveats.
#
# AUTO-GENERATED by `mix glorbo.release_formula` — do not edit
# by hand. Regenerate after each release:
#
#   gh release create vX.Y.Z ...
#   mix glorbo.release_formula --write
class Glorbo < Formula
  desc "Filesystem-first agent orchestration (Elixir/OTP + Phoenix LiveView)"
  homepage "https://github.com/foobarto/glorbo"
  version "0.21.1"
  license "Apache-2.0"

  on_linux do
    # bwrap is the kernel-enforced sandbox around every agent
    # subprocess (GEP-5 D4). Linux-only: macOS has no equivalent
    # yet.
    depends_on "bubblewrap"

    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.21.1/glorbo-linux-x86_64"
      sha256 "71db82229a58be67d567faa660bdb586ebc54ef9e1905345023e060c98811658"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.21.1/glorbo-linux-aarch64"
      sha256 "b8799c8f6661d34620b59db9d600f68125e5d185c5d024b5e5eea1f63990d67a"
    end
  end

  on_macos do
    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.21.1/glorbo-darwin-x86_64"
      sha256 "274efc5421045647bac0b486c56d5e0c7fa77c52c7bd5d10c56ebcfa1dd16d02"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.21.1/glorbo-darwin-arm64"
      sha256 "564d30c4b932acedbfcc812e00971b53cf9d9732aaa74523c140c6d6090cbfd2"
    end
  end

  def install
    # Burrito ships a single self-contained binary. Pick the right
    # downloaded file by OS + CPU and rename to `glorbo`.
    binary =
      if OS.mac?
        Hardware::CPU.intel? ? "glorbo-darwin-x86_64" : "glorbo-darwin-arm64"
      else
        Hardware::CPU.intel? ? "glorbo-linux-x86_64" : "glorbo-linux-aarch64"
      end

    bin.install binary => "glorbo"
    chmod 0755, bin/"glorbo"
  end


  def caveats
    <<~EOS
      Glorbo is pre-1.0. APIs, CLI flags, on-disk layout, and the
      SQLite schema may change between minor versions.

      First-run setup:
        glorbo doctor          # verify host prerequisites
        glorbo init            # scaffold ~/.glorbo/ with an acme example
        glorbo up              # start the dashboard on :4000

      Platform notes:

      Linux  — agents run in a bwrap-sandboxed subprocess (GEP-5).
               `brew install bubblewrap` is declared as a dep.

      macOS  — experimental. Agents run UNSANDBOXED because bwrap
               has no macOS equivalent yet. `glorbo doctor` flags
               this with a warning; a single audit row lands at
               first dispatch (`agent.sandbox_unavailable`).
               FSEvents covers the filesystem-watcher side.

      Docs: #{homepage}
    EOS
  end

  test do
    # Doctor in JSON mode returns the version + check list.
    output = shell_output("#{bin}/glorbo doctor --json")
    assert_match(/"version":\s*"0\\.21\\.1"/, output)
    assert_match(/"checks":/, output)
  end
end
