# typed: false
# frozen_string_literal: true

# Homebrew formula for Glorbo — filesystem-first agent orchestration.
#
# Pre-1.0. Linux: full kernel-sandboxed agent runtime via bwrap
# (GEP-5). macOS: degraded mode — agents run unsandboxed because
# bwrap has no macOS equivalent yet. See caveats.
#
# AUTO-GENERATED by `mix glorbo.release_formula` — do not edit
# by hand. Regenerate after each release:
#
#   gh release create vX.Y.Z ...
#   mix glorbo.release_formula --write
class Glorbo < Formula
  desc "Filesystem-first agent orchestration (Elixir/OTP + Phoenix LiveView)"
  homepage "https://github.com/foobarto/glorbo"
  version "0.8.0"
  license "Apache-2.0"

  on_linux do
    # bwrap is the kernel-enforced sandbox around every agent
    # subprocess (GEP-5 D4). Linux-only: macOS has no equivalent
    # yet.
    depends_on "bubblewrap"

    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.8.0/glorbo-linux-x86_64"
      sha256 "c1164ee5e2024517def56d4896f46c336c6bd07b4b0ae788961a0dd3d56eb29f"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.8.0/glorbo-linux-aarch64"
      sha256 "e85c0f150b7add42eb3de01b6f2f2b11dc182fa0690d9acdfcd43a3e201c5096"
    end
  end

  on_macos do
    on_intel do
      url "https://github.com/foobarto/glorbo/releases/download/v0.8.0/glorbo-darwin-x86_64"
      sha256 "296879ea8a03143d423d288c58d63e8541c7a0e1ef87e7cf02d09186e00c5559"
    end

    on_arm do
      url "https://github.com/foobarto/glorbo/releases/download/v0.8.0/glorbo-darwin-arm64"
      sha256 "43e51e16a798e7a1db6ff3bf16b6837a162f68e95b644453f628e4ba71be60eb"
    end
  end

  def install
    # Burrito ships a single self-contained binary. Pick the right
    # downloaded file by OS + CPU and rename to `glorbo`.
    binary =
      if OS.mac?
        Hardware::CPU.intel? ? "glorbo-darwin-x86_64" : "glorbo-darwin-arm64"
      else
        Hardware::CPU.intel? ? "glorbo-linux-x86_64" : "glorbo-linux-aarch64"
      end

    bin.install binary => "glorbo"
    chmod 0755, bin/"glorbo"
  end


  def caveats
    <<~EOS
      Glorbo is pre-1.0. APIs, CLI flags, on-disk layout, and the
      SQLite schema may change between minor versions.

      First-run setup:
        glorbo doctor          # verify host prerequisites
        glorbo init            # scaffold ~/.glorbo/ with an acme example
        glorbo up              # start the dashboard on :4000

      Platform notes:

      Linux  — agents run in a bwrap-sandboxed subprocess (GEP-5).
               `brew install bubblewrap` is declared as a dep.

      macOS  — experimental. Agents run UNSANDBOXED because bwrap
               has no macOS equivalent yet. `glorbo doctor` flags
               this with a warning; a single audit row lands at
               first dispatch (`agent.sandbox_unavailable`).
               FSEvents covers the filesystem-watcher side.

      Docs: #{homepage}
    EOS
  end

  test do
    # Doctor in JSON mode returns the version + check list.
    output = shell_output("#{bin}/glorbo doctor --json")
    assert_match(/"version":\s*"0\\.8\\.0"/, output)
    assert_match(/"checks":/, output)
  end
end
