# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stado < Formula
  desc "Sandboxed, git-native coding-agent runtime"
  homepage "https://github.com/foobarto/stado"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foobarto/stado/releases/download/v0.4.2/stado_0.4.2_darwin_amd64.tar.gz"
      sha256 "3c24731cafd62410469e844762976b14743ce3d038842d391055277adcbddd96"

      define_method(:install) do
        bin.install "stado"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foobarto/stado/releases/download/v0.4.2/stado_0.4.2_darwin_arm64.tar.gz"
      sha256 "ad25088690ebb6a786aa1c8e55491bc66d272aa0656c2b1372af04ac516f5e23"

      define_method(:install) do
        bin.install "stado"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foobarto/stado/releases/download/v0.4.2/stado_0.4.2_linux_amd64.tar.gz"
      sha256 "fec7aa2d6f2571f54ae4f402787cfe09b13b17c1c6acf2a2390936336d63411d"
      define_method(:install) do
        bin.install "stado"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foobarto/stado/releases/download/v0.4.2/stado_0.4.2_linux_arm64.tar.gz"
      sha256 "c18a3cfbbd3fe4452d5dfd027038ef2fcfadc332524dcdc0416f3e5d9f90d51c"
      define_method(:install) do
        bin.install "stado"
      end
    end
  end

  test do
    system "#{bin}/stado", "version"
  end
end
