# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stado < Formula
  desc "Sandboxed, git-native coding-agent runtime"
  homepage "https://github.com/foobarto/stado"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/foobarto/stado/releases/download/v0.2.1/stado_0.2.1_darwin_amd64.tar.gz"
      sha256 "ccb2abb7eaaba9969feb9ed8b86a075daec1f8cb6ef0f4113a9229f6acc7c69e"

      define_method(:install) do
        bin.install "stado"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/foobarto/stado/releases/download/v0.2.1/stado_0.2.1_darwin_arm64.tar.gz"
      sha256 "ff93b48a75d0612214205d92f5fb8336249e76f01d4e8a983633a081c330b596"

      define_method(:install) do
        bin.install "stado"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/foobarto/stado/releases/download/v0.2.1/stado_0.2.1_linux_amd64.tar.gz"
      sha256 "5b13e8714857148648ebcb5d0b22369622f38a0cea40d605c3fc091e9a5a045a"
      define_method(:install) do
        bin.install "stado"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/foobarto/stado/releases/download/v0.2.1/stado_0.2.1_linux_arm64.tar.gz"
      sha256 "0d42fe05528bbedb305ff60a5031b7cc979f2232359115e46ddabfa027173406"
      define_method(:install) do
        bin.install "stado"
      end
    end
  end

  test do
    system "#{bin}/stado", "version"
  end
end
